### ISSUE TITLE
Can this be updated?

### ISSUE THREAD

**Issue by rnd-ash** [marcelbuesing/socketcan-isotp#7]
Just a request, I am trying to publish a new version of my [ecu diagnostics crate](https://docs.rs/ecu_diagnostics/latest/ecu_diagnostics/)

I submitted #6 a few weeks ago to fix some major issues with certain slower ECUs (It was merged), but in order to publish the fixed crate, this crate needs to be updated first.

**Comment by marcelbuesing** [comment]
That looks like a great crate! I just published 1.0.1 of socketcan-isotp containing the changes.
